FROM node:lts-slim

WORKDIR /app

COPY package.json .
ARG BUILD_DEPS="python-dev make g++ gcc"

RUN apt-get update

RUN apt-get install -y $BUILD_DEPS

RUN npm install; exit 0

RUN apt-get purge --auto-remove -y $BUILD_DEPS \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
              /tmp/* \
              /var/tmp/* \
              /usr/share/man \
              /usr/share/doc \
              /usr/share/doc-base
COPY . .

EXPOSE 1234

CMD ["npm", "run", "start"]